apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openvpn-as
  namespace: openvpn
spec:
  interval: 1h
  url: https://github.com/OpenVPN/as-helm-chart.git
  ref:
    branch: main
